version: '3.9'

services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: navystack/nodebb:3.6.6
    volumes:
      - nodebb-data:/usr/src/app
      - ./setup.json:/usr/src/app/setup.json
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.services.nodebb.loadbalancer.server.port=4567'
      - 'traefik.http.services.nodebb.loadbalancer.passhostheader=true'
      - 'traefik.http.routers.nodebb-rt.entrypoints=websecure'
      - 'traefik.http.routers.nodebb-rt.rule=Host(`example.com`) || Host(`www.example.com`)'
      - 'traefik.http.routers.nodebb-rt.service=nodebb'
      - 'traefik.http.routers.nodebb-rt.middlewares=www-to-Root@file, security-headers@file, websocket@file'
      - 'traefik.http.routers.nodebb-rt.tls=true'
      - 'traefik.http.routers.nodebb-rt.tls.certresolver=letsencrypt'
    networks:
      - traefik-network
      - interanl

  mongo:
    container_name: mongo
    image: navystack/nodebb:mongo7-latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: nodebb
      MONGO_INITDB_ROOT_PASSWORD: TwDOp3phPKTvLG9we4rjx3xdJmlD51
      MONGO_INITDB_DATABASE: nodebb
    volumes:
      - mongo-data:/data/db
      - ./nodebb-mongo-init.js:/docker-entrypoint-initdb.d/user-init.js
    networks:
      - interanl

volumes:
  mongo-data:
  nodebb-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./data/

networks:
  traefik-network:
    external: true
  interanl:
