version: '3.9'

services:
  nodebb:
    container_name: nodebb
    restart: unless-stopped
    image: navystack/nodebb:3.6.6
    volumes:
      - ./setup.json:/usr/src/app/setup.json
      - nodebb-config:/opt/config
      - nodebb-build:/usr/src/app/build
      - nodebb-uploads:/usr/src/app/public/uploads
      - nodebb-modules:/usr/src/app/node_modules
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-network'
      - 'traefik.http.services.nodebb.loadbalancer.server.port=4567'
      - 'traefik.http.services.nodebb.loadbalancer.passhostheader=true'
      - 'traefik.http.routers.nodebb-rt.entrypoints=websecure'
      - 'traefik.http.routers.nodebb-rt.rule=Host(`navystack.com`) || Host(`www.navystack.com`)'
      - 'traefik.http.routers.nodebb-rt.service=nodebb'
      - 'traefik.http.routers.nodebb-rt.middlewares=www-to-Root@file, security-headers@file, websocket@file'
      - 'traefik.http.routers.nodebb-rt.tls=true'
    networks:
      - traefik-network
      - interanl

  mongo:
    container_name: mongo
    image: navystack/nodebb:mongo7-latest
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: navystack-mongo
      MONGO_INITDB_ROOT_PASSWORD: lyFn5aQepK5Q8e6o6GC5HgvWktE2vb
      MONGO_INITDB_DATABASE: navystack-mongo
    volumes:
      - mongo-data:/data/db
      - ./nodebb-mongo-init.js:/docker-entrypoint-initdb.d/user-init.js
    networks:
      - interanl

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: navystack-mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: lyFn5aQepK5Q8e6o6GC5HgvWktE2vb
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - interanl

  redis:
    image: redis:7.2.3-alpine
    restart: unless-stopped
    volumes:
      - ./.docker/database/redis:/data
    networks:
      - interanl

volumes:
  nodebb-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/
  nodebb-build:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./build/
  nodebb-uploads:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./uploads/
  nodebb-modules:
  mongo-data:

networks:
  traefik-network:
    external: true
  interanl:
